spring:
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      host: mongo
      port: 27017
      username: devuser
      password: devpassword
      database: springboot_chat
logging:
  level:
    org:
      mongodb:
        core:
          MongoTemplate: debug